<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.test</groupId>
    <artifactId>build-parent</artifactId>
    <version>1.7.0</version>
  </parent>
  <groupId>com.test</groupId>
  <artifactId>test</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>test</name>
  <description>An example pom file</description>
  <modules>
    <module>test-module-1</module>
    <module>test-module-2</module>
    <module>test-module-3</module>
  </modules>
  <properties>
    <!-- Maven Repos -->
    <maven.repo.id>maven-releases</maven.repo.id>
    <maven.repo.url>https://release-PLACEHOLDER/repository/maven-releases</maven.repo.url>
    <maven.snapshot.repo.id>maven-snapshots</maven.snapshot.repo.id>
    <maven.snapshot.repo.url>https://snapshot-PLACEHOLDER/repository/maven-snapshots</maven.snapshot.repo.url>
    <pypi.project.repository.url>https://pypi-PLACEHOLDER/repository/</pypi.project.repository.url>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.test</groupId>
        <artifactId>test-dep-management-1</artifactId>
        <version>${version.test}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.test</groupId>
        <artifactId>test-dep-management-2</artifactId>
        <version>${version.test}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <scm>
    <connection>scm:git:url.git</connection>
    <developerConnection>scm:git:url.git</developerConnection>
    <url>url</url>
    <tag>HEAD</tag>
  </scm>
  <distributionManagement>
    <repository>
      <id>${maven.repo.id}</id>
      <url>${maven.repo.url}</url>
    </repository>
    <snapshotRepository>
      <id>${maven.snapshot.repo.id}</id>
      <url>${maven.snapshot.repo.url}</url>
    </snapshotRepository>
  </distributionManagement>
  <repositories>
    <repository>
      <id>${maven.repo.id}</id>
      <url>${maven.repo.url}</url>
      <releases>
        <enabled>true</enabled>
        <checksumPolicy>fail</checksumPolicy>
      </releases>
    </repository>
    <repository>
      <id>${maven.snapshot.repo.id}</id>
      <url>${maven.snapshot.repo.url}</url>
      <snapshots>
        <enabled>true</enabled>
        <checksumPolicy>fail</checksumPolicy>
      </snapshots>
    </repository>
  </repositories>
  <build>
    <extensions>
      <extension>
        <groupId>com.test</groupId>
        <artifactId>test-extension</artifactId>
        <version>${version.test}</version>
      </extension>
    </extensions>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.test</groupId>
          <artifactId>test-plugin-management-1</artifactId>
          <dependencies>
            <dependency>
              <groupId>com.test</groupId>
              <artifactId>test-plugin-management-1-deps</artifactId>
              <version>${version.test}</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <groupId>com.test</groupId>
          <artifactId>test-plugin-management-2</artifactId>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>com.test</groupId>
        <artifactId>test-plugin-1</artifactId>
        <inherited>false</inherited>
        <dependencies>
          <dependency>
            <groupId>com.test</groupId>
            <artifactId>test-plugin-1-dep</artifactId>
            <version>${version.test}</version>
          </dependency>
        </dependencies>
      </plugin>
      <plugin>
        <groupId>com.test</groupId>
        <artifactId>test-plugin-2</artifactId>
        <inherited>false</inherited>
        <configuration>
          <basePackage>com.test</basePackage>
          <profile>test-project-root</profile>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.test</groupId>
        <artifactId>test-plugin-3</artifactId>
        <version>${version.test}</version>
        <configuration>
          <config1>test-plugin-3-config-1</config1>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.test</groupId>
        <artifactId>test-plugin-4</artifactId>
        <executions>
          <execution>
            <id>test-plugin-4-execution-1</id>
            <goals>
              <goal>test-plugin-4-execution-1-goal-1</goal>
            </goals>
            <configuration>
              <config1>test-plugin-4-config-1</config1>
              <config2>test-plugin-4-config-2</config2>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
